#  https://www.codingame.com/ide/puzzle/fix-the-spaces
import sys,math

def sucheSpace(original,wordList):
    pos=0;leerList=[];spaceList=[];saveList=[];count=0
    while pos < len(original):
        xWord=""
        for word in wordList:
            if original[pos:pos+len(word)] == word:
                xWord=word;break
        if len(xWord) == 0: # one back
            if saveList == leerList:
                count+=1
                if count > 9:
                    return []
            saveList = leerList[:]
            xWord = leerList.pop();spaceList.pop()        
            pos-=len(xWord);wordList.append(xWord)
            
            #print("fehler");exit(0)
        else:
            spaceList.append(pos)
            leerList.append(xWord)
            pos+=len(xWord)
            wordList.remove(xWord)   
        
    return spaceList

original = 'ABCDEABABCABCD'
words = 'ABCD AB ABC ABCDE'

original='LOREMIPSUMDOLORSITAMETCONSECTETURADIPISCINGELITSEDDOEIUSMODTEMPORINCIDIDUNTUTLABOREETDOLOREMAGNAALIQUAESTLIBEROMOLESTIEACCUMSANDUIACRISUSINCEPTOSHABITASSEHABITASSEFINIBUSAORNAREINTERDUMVITAEHIMENAEOSAUGUEPHASELLUSSAPIENSITSOCIOSQUPHARETRAFINIBUSMORBIALIQUETTINCIDUNTCLASSESTDIAMHABITASSEFEUGIATMAGNAPROINMAURISVIVAMUSTINCIDUNTALIQUETNIBHALIQUAMACUBILIATELLUSLEOFELISALIQUAMVOLUTPATANTENAMVITAEDOLORPRETIUMTELLUSGRAVIDACONGUEALIQUETFAMESCONDIMENTUMNUNCNULLADIAMPRAESENTEGESTASTORTORALIQUETCONDIMENTUMFUSCEVULPUTATEPURUSINTERDUMMAURISULTRICESPULVINARFINIBUSNEQUELIGULALUCTUSNULLAMDAPIBUSBLANDITACDOLORVEHICULAMOLESTIELAOREETPLATEATINCIDUNTSAPIENPURUSNISLMOLLISIPSUMMINISIVELITHENDRERITSEDELEMENTUMCURABITURMAURISPHARETRAUTARCUSUSCIPITQUISVENENATISFAMESFEUGIATVELITNETUSBLANDITCONUBIAVELPROINPOSUEREVEHICULALAOREETCRASSEMPERMAXIMUSFINIBUS'
words = 'PRETIUM DOLORE VEHICULA FINIBUS ET ALIQUAM VELIT MOLESTIE ALIQUET CONDIMENTUM MAURIS CONDIMENTUM PROIN LIBERO CRAS MI AC TINCIDUNT NISL HABITASSE VITAE EST MOLESTIE VEHICULA MOLLIS FAMES AMET NAM UT CLASS ANTE HIMENAEOS DIAM NUNC BLANDIT NETUS NIBH IPSUM SED A QUIS NEQUE SAPIENPURUS ULTRICES AC LOREM FAMES UT LAOREET SUSCIPIT ALIQUET VULPUTATE SEMPER ALIQUAM FELIS TELLUS NULLA TINCIDUNT INTERDUM CONGUE ALIQUET MAXIMUS NISI LEO POSUERE LIGULA FEUGIAT HABITASSE RISUS TEMPOR INTERDUM PROIN ADIPISCING FINIBUS PHARETRA TORTOR ELEMENTUM VELIT INCEPTOS VEL ELIT DOLOR A DO CONSECTETUR LUCTUS BLANDIT VENENATIS FEUGIAT MAGNA TELLUSGRAVIDA MAURIS VITAE PHARETRA SAPIEN ALIQUA CUBILIA DOLOR PULVINAR DUI LAOREET FINIBUS PURUS DIAM MORBI EIUSMOD PLATEA MAGNA CURABITUR ORNARE PRAESENT DOLOR NULLAM EGESTAS TINCIDUNT LABORE IPSUM CONUBIA FUSCE INCIDIDUNT SIT FINIBUS MAURIS VOLUTPAT ARCU AUGUE HENDRERIT SOCIOSQU HABITASSE SIT EST ACCUMSAN PHASELLUS SED ALIQUET VIVAMUS DAPIBUS'

#original='ABCEDFEDFABC'
#words='EDF EDF ABC ABC'

#original='ABABCDCDEABCDEABCD'
#words='CDE AB ABCD CDE ABCD AB'    #  AB ABCD CDE AB CDE ABCD

#original='STARSTARSTAR'
#words='STARS TAR STAR'

original='ABCABABC'
words='AB ABC CAB'

fehler="Unsolvable";ausgabe=original
wordList=[]
wordList = words.split(" ")
word2List=sorted(wordList)
if wordList == word2List:
    word2List=sorted(wordList,reverse=True)

spaceList=sucheSpace(original,wordList)

spaceTest=sucheSpace(original,word2List)     


print(spaceList,file=sys.stderr)
for sp in sorted(spaceList,reverse=True):
    original = original[:sp] + " " + original[sp:]

if spaceList == spaceTest or len(spaceTest) == 0:
#if len(wordList) == 0:
    print(original[1:])
else:
    print(fehler)